# .github/workflows/code_checks.yaml
name: Code_Checks

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4']

    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, zip, zlib
          coverage: xdebug

      - name: Download dependencies
        run: composer update --no-ansi --prefer-stable --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover
      - name: Static analysis for source
        run: ./vendor/bin/phpstan analyse -l max src
      - name: Static analysis for tests
        run: ./vendor/bin/phpstan analyse -l 5 test
      - name: Code Style
        run: ./vendor/bin/php-cs-fixer fix --dry-run --verbose --config .php_cs.dist ./src ./test